### ISSUE TITLE
Failed to install lwipfy

### ISSUE THREAD

**Issue by slidenerd** [IonicaBizau/lwipify#9]
First of all, thank you for the awesome work on the library, i was trying to install it and got this issue
```
> lwip2@1.0.3 install D:\bots\qrbot\node_modules\lwip2
> node scripts/install.js

Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN qrbot@1.0.0 No description
npm WARN qrbot@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "lwipify"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! lwip2@1.0.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip2@1.0.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\bots\qrbot\npm-debug.log
```

I understand it needs some external dependency from this error but I am not sure how to go about that external dependency, any suggestions.

It says, if it fails install GraphicsMagick, does it want an exe file or npm module for graphics magick

**Comment by IonicaBizau** [comment]
Hmm, looks it doesn't find `npm` in the PATH. What do `npm --version` and `node --version` output?

**Comment by slidenerd** [comment]
npm --version = 3.10.8 and node --version = 6.9.1

**Comment by reppners** [comment]
The issue is how lwip2 tries to install the necessary package:
https://github.com/IonicaBizau/lwip2/blob/918c8817755f798287e38d47ba0f63c09a0f244f/lib/install.js#L15

On Windows this fails because npm needs to be invoked as `npm.cmd`.

**Comment by IonicaBizau** [comment]
Oh, didn't know about `npm.cmd`!

**Comment by IonicaBizau** [comment]
@reppners Can you do an `npm install` either in this repo or `image-to-ascii` to get the latest `lwip2`? Hopefully this works. I cannot test it right now.

**Comment by reppners** [comment]
works 👍

**Comment by IonicaBizau** [comment]
🎉
